/*
 * This source file was generated by the Gradle 'init' task
 */
package team.techtigers.tutorials;

public class App {
    public static void main(String[] args) {
        Car car = new Car();
        car.show();
        car.rentCar("Honda", "Corolla");

    }
}
