/*
 * This source file was generated by the Gradle 'init' task
 */
package team.techtigers.tutorials;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, world!");
    }
}
