[versions]
mockito = "5.12.0"
junit-jupiter = "5.10.3"

[libraries]
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
junit-jupiter = { group="junit-jupiter", module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-params = { group="junit-jupiter", module ='org.junit.jupiter:junit-jupiter-params', version.ref='junit-jupiter' }

[plugins]
java-application = { id = "application" }
testlogger = { id = "com.adarshr.test-logger", version = "4.0.0" }
